name: Clean Build Android

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    
    - name: Set up JDK 17
      uses: actions/setup-java@3a4f6e1af50496a3185856a474b17a3490b742d8
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      run: |
        cd streamfree-music-android
        gradle assembleDebug
      working-directory: .

    - name: Upload APK
      uses: actions/upload-artifact@4cec3d8aa04e39d727839c1b20f535e19e510854
      with:
        name: streamfree-music-debug
        path: streamfree-music-android/app/build/outputs/apk/debug/app-debug.apk
